// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -O2 -emit-llvm -o - %s | FileCheck %s

#line 4 "attr-callsite-wrapper.c"

#define __callsite_wrapper __attribute__((callsite_wrapper))

__callsite_wrapper
static inline unsigned int callsite_line(void) {
#line 10
    return __builtin_LINE();
}

// CHECK-LABEL: define dso_local noundef i32 @callsite_line_call(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret i32 20
//
unsigned int callsite_line_call(void) {
#line 20
    return callsite_line();
}

// CHECK-LABEL: define dso_local noundef i32 @callsite_line_multitple_calls_same_line(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret i32 3030
//
unsigned int callsite_line_multitple_calls_same_line() {
#line 30
    return callsite_line() * 100 +  callsite_line();
}

__callsite_wrapper
static inline unsigned int callsite_column(void) { return __builtin_COLUMN(); }


// CHECK-LABEL: define dso_local noundef i32 @callsite_column_call(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret i32 12
//
unsigned int callsite_column_call(void) {
    return callsite_column();
}

// CHECK-LABEL: define dso_local noundef i32 @callsite_column_multitple_calls_same_line(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret i32 1238
//
unsigned int callsite_column_multitple_calls_same_line() {
    return callsite_column() * 100 + callsite_column();
}

__callsite_wrapper
static inline const char* callsite_file(void) {
    return __builtin_FILE();
}

// CHECK-LABEL: define dso_local noundef nonnull ptr @callsite_file_call(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret ptr @.str
//
const char* callsite_file_call(void) {
    return callsite_file();
}

#line 70 "some-include.h"
// CHECK-LABEL: define dso_local noundef nonnull ptr @callsite_file_call_from_include(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret ptr @.str.1
//
const char* callsite_file_call_from_include(void) {
    return callsite_file();
}

__attribute__((callsite_wrapper))
static inline const char* callsite_file_include(void) {
    return __builtin_FILE();
}
#line 84 "attr-callsite-wrapper.c"

// CHECK-LABEL: define dso_local noundef nonnull ptr @callsite_file_include_call(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret ptr @.str
//
const char* callsite_file_include_call(void) {
    return callsite_file_include();
}

__callsite_wrapper
static inline const char* callsite_function(void) {
    return __builtin_FUNCTION();
}

// CHECK-LABEL: define dso_local noundef nonnull ptr @callsite_function_call1(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret ptr @.str.2
//
const char* callsite_function_call1(void) {
    return callsite_function();
}

// CHECK-LABEL: define dso_local noundef nonnull ptr @callsite_function_call2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret ptr @.str.3
//
const char* callsite_function_call2(void) {
    return callsite_function();
}

// CHECK-LABEL: define dso_local void @callsite_function_call3(
// CHECK-SAME: ptr nocapture noundef writeonly [[RESULT1:%.*]], ptr nocapture noundef writeonly [[RESULT2:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    store ptr @.str.4, ptr [[RESULT1]], align 8, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    store ptr @.str.4, ptr [[RESULT2]], align 8, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
void callsite_function_call3(const char** result1, const char** result2) {
    *result1 = callsite_function();
    *result2 = callsite_function();
}

__callsite_wrapper
static inline const char* nested_callsite_function(void) {
    return callsite_function();
}

// CHECK-LABEL: define dso_local noundef nonnull ptr @nested_callsite_function_call1(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret ptr @.str.5
//
const char* nested_callsite_function_call1(void) {
    return nested_callsite_function();
}

// CHECK-LABEL: define dso_local noundef nonnull ptr @nested_callsite_function_call2(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret ptr @.str.6
//
const char* nested_callsite_function_call2(void) {
    return nested_callsite_function();
}

__callsite_wrapper
static inline unsigned int recursive_callsite_line(int depth) {
    if (depth == 0) {
        return __builtin_LINE();
    }
#line 158
    return recursive_callsite_line(depth - 1);
}

// CHECK-LABEL: define dso_local noundef i32 @recursive_callsite_line_call(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret i32 168
//
unsigned int recursive_callsite_line_call(void) {
#line 168
    return recursive_callsite_line(1);
}
//.
// CHECK: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// CHECK: [[META3]] = !{!"any pointer", [[META4:![0-9]+]], i64 0}
// CHECK: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// CHECK: [[META5]] = !{!"Simple C/C++ TBAA"}
//.
